version: '3'

services:
  plugin:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - schema
    volumes:
      - ./cassandraSchemas/:/usr/src/app/cassandraSchemas:ro
      - ./cassandraConfig/:/usr/src/app/cassandraConfig:ro

  schema:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "schema"]
    env_file:
      - .env
    volumes:
      - ./cassandraSchemas/:/usr/src/app/cassandraSchemas:ro
      - ./cassandraConfig/:/usr/src/app/cassandraConfig:ro
