version: '3'

services:
  plugin:
    build:
      context: .
      dockerfile: Dockerfile.plugin
    environment:
      ENVSEPARATOR: _
      PLUGIN_USER_LOGIN: dhadmin
      PLUGIN_USER_PASSWORD: dhadmin_#911
      PLUGIN_PLUGIN_TOPIC: plugin_topic_a2bb68c2-b288-40dd-aa08-41639c4cf308
      PLUGIN_DEVICE_HIVE_PLUGIN_WS_ENDPOINT: ws://192.168.152.174:3001
      PLUGIN_DEVICE_HIVE_AUTH_SERVICE_API_URL: http://192.168.152.174:8090/dh/rest
      PLUGIN_SUBSCRIPTION_GROUP: cassandra_plugin
      CASSANDRA_CONNECTION_KEYSPACE: testks
      CASSANDRA_CONNECTION_USERNAME: cassandra
      CASSANDRA_CONNECTION_PASSWORD: cassandra
      CASSANDRA_CUSTOM_SCHEMA_CHECKS_COUNT: 10
      CASSANDRA_CUSTOM_SCHEMA_CHECKS_INTERVAL: 500
      CASSANDRA_CONNECTION_CONTACT_POINTS: 192.168.152.174
    depends_on:
      - schema
  schema:
    build:
      context: .
      dockerfile: Dockerfile.schema
    environment:
      ENVSEPARATOR: _
      CASSANDRA_CONNECTION_KEYSPACE: testks
      CASSANDRA_CONNECTION_USERNAME: cassandra
      CASSANDRA_CONNECTION_PASSWORD: cassandra
      CASSANDRA_CONNECTION_CONTACT_POINTS: 192.168.152.174